### ISSUE TITLE
How to use it in Scala 2.12.2?

### ISSUE THREAD

**Issue by zchazc** [tuxBurner/play-akkjobs#1]
Hello, I am a beginner at Play!
And I want to use a task lib in my project(2.6.6 with Scala 2.12.2).
Then I try those way:
write "libraryDependencies += "com.github.tuxBurner" % "play-akkajobs_2.11" % "1.0.1"" at build.sbt;
update Scala version from 2.12.2 to 2.11;
download lib and move it under src/libs;
All of those were not work,now,I don't know what should I do...

**Comment by tuxBurner** [comment]
Hi @zchazc i have to lift it to play 2.6

**Comment by tuxBurner** [comment]
Hi @zchazc  i lifted the library to version 2.6.0 so it is now compatible with play 2.6.x.

**Comment by zchazc** [comment]
Thank you ~!
:)
