### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by marcosinigaglia** [tuxBurner/play-akkjobs#2]
https://github.com/tuxBurner/play-akkjobs/blob/f9208c2143874070463903fcd122b1602f28d117/src/main/java/com/github/tuxBurner/jobs/AbstractAkkaJob.java#L81

Hi, I think the calculation for the `nextFireDate` is wrong, you use `getNextInterval ` method that 
> Return the interval between the next valid date and the one after

So if my cron expression id `0 3 18 * * ? * *` the method return always 24h (86400000 milliseconds).

**Comment by tuxBurner** [comment]
Uhhh thanks @marcosinigaglia i take a look at it.

**Comment by tuxBurner** [comment]
Hey @marcosinigaglia i think i fixed it :)

For Play 2.6 use version 2.6.1
For Play 2.5 use version 1.0.2

Thanks for finding out.

**Comment by marcosinigaglia** [comment]
Thanks

**Comment by tuxBurner** [comment]
Of course thanks again for finding this bug :)
