### ISSUE TITLE
usage in non Guice applicationloader

### ISSUE THREAD

**Issue by Raffiki** [tuxBurner/play-akkjobs#4]
question: how could I use this module in a custom application loader? Is this possible at all?

**Comment by tuxBurner** [comment]
Hi @Raffiki what version of play are you using ?
Since 2.5 Guice is brought by Play so it should be no hassle to use it there :)
What is your project  layout to have not Guice ?

**Comment by tuxBurner** [comment]
@Raffiki what you could do is to instantiate the JobClassLoader.java and than it should work without Guice.
Keep in mind to only instantiate this class once, it is a singleton purpose class.
